# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarchive',
            name='archived',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postarchive',
            name='archived',
            field=models.DateField(auto_now_add=True),
        ),
    ]
