# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0002_auto_20170812_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='latest',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='merged_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged', to='closedverse_main.Notification'),
        ),
    ]
