# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0003_community_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drawing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
