# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0004_auto_20170813_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='relation_visibility',
            new_name='relationship_visibility',
        ),
    ]
