# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0005_auto_20170904_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.CharField(blank=True, choices=[('announcements', 'main announcement community'), ('changelog', 'main changelog'), ('activity', 'Activity Feed posting community')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'general'), (1, 'game'), (2, 'special'), (3, 'hide')], default=0),
        ),
    ]
