# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0007_yeah'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeah',
            name='by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yeah',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Comment'),
        ),
        migrations.AlterField(
            model_name='yeah',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Post'),
        ),
    ]
