# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0007_auto_20170908_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
