# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0008_auto_20170909_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allowed_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
