# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0009_yeah_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='drawing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
