# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0009_auto_20170816_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='special_tag',
        ),
    ]
