# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0009_community_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
