# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0010_remove_community_special_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='special_tag',
            field=models.CharField(blank=True, choices=[('announcements', 'main announcements'), ('info', 'main changelog')], max_length=255, null=True, unique=True),
        ),
    ]
