# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0010_auto_20170909_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
    ]
