# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0011_auto_20170909_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'general'), (1, 'game'), (2, 'special'), (3, 'hide'), (4, 'feature')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'urapp'), (2, 'moderator'), (3, 'admin'), (5, 'pf2m'), (10, 'master')], default=0),
        ),
    ]
