# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0011_community_special_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='special_tag',
            new_name='tag',
        ),
    ]
