# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0012_auto_20170910_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'general'), (1, 'game'), (2, 'special'), (3, 'hide')], default=0),
        ),
    ]
