# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0012_auto_20170816_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tag',
            field=models.CharField(blank=True, choices=[('announcements', 'main announcements'), ('info', 'main changelog')], max_length=255, null=True),
        ),
    ]
