# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0013_auto_20170910_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('able_vote', models.BooleanField(default=True)),
                ('choices', models.TextField(default='[]')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
