# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0014_communityfavorite_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.DateTimeField(auto_now_add=True)),
                ('choice', models.SmallIntegerField(default=0)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Poll')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Poll'),
        ),
    ]
