# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0014_auto_20170816_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='tags',
        ),
    ]
