# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0015_auto_20170915_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_let_yeahnotifs',
            field=models.BooleanField(default=False),
        ),
    ]
