# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0016_community_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='finished',
        ),
    ]
