# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0017_auto_20170806_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link',
            new_name='weblink',
        ),
    ]
