# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0018_auto_20170806_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_visibility',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
