# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0018_message_is_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_rm',
            field=models.BooleanField(default=False),
        ),
    ]
