# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0020_auto_20170918_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login',
            new_name='recent',
        ),
    ]
