# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0020_auto_20170810_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feeling',
            field=models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused')], default=0),
        ),
    ]
