# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0021_auto_20170919_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_gravatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='has_gravatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
