# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0022_community_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
