# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0023_auto_20170920_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='let_presence_view',
            field=models.BooleanField(default=True),
        ),
    ]
