# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0024_profile_let_presence_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='let_freedom',
            field=models.BooleanField(default=False),
        ),
    ]
