# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0025_profile_let_freedom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermostatTouch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='let_freedom',
            field=models.BooleanField(default=True),
        ),
    ]
