# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0026_auto_20170926_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adopted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thermostattouch',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='screenshot',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='ico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='screenshot',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='screenshot',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
    ]
