# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0027_auto_20170929_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='origin_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='feeling',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused'), (69, 'easter egg')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='feeling',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused'), (69, 'easter egg')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused'), (69, 'easter egg')], default=0),
        ),
    ]
