# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0028_auto_20171005_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='let_presence_view',
        ),
    ]
