# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0029_remove_profile_let_presence_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_gravatar',
        ),
        migrations.AddField(
            model_name='user',
            name='has_mh',
            field=models.BooleanField(default=False),
        ),
    ]
