# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0030_auto_20171005_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gameskill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship_visibility',
        ),
    ]
