# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0031_auto_20171005_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='origin_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
