# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityclink',
            name='also',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='closedverse_main.Community'),
        ),
        migrations.AlterField(
            model_name='communityclink',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='closedverse_main.Community'),
        ),
    ]
