# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0002_auto_20170730_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
