# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0008_auto_20170801_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeah',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
