# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0011_auto_20170804_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=1200)),
                ('gameskill', models.PositiveSmallIntegerField(default=0)),
                ('favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
