# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0013_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='screenshot',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='post',
            name='screenshot',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
    ]
