# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0014_auto_20170806_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
