# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0015_follow_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
