# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0016_auto_20170806_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
    ]
