# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0019_profile_id_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relation_visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'show'), (1, 'friends only'), (2, 'hide')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='feeling',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, '3ds'), (2, 'wii u'), (3, 'both')], default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'general'), (1, 'game'), (2, 'special')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, ''), (2, ''), (3, ''), (4, ''), (5, '')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'show'), (1, 'friends only'), (2, 'hide')], default=0),
        ),
        migrations.AlterField(
            model_name='yeah',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'post'), (1, 'comment')], default=0),
        ),
    ]
