# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0023_follow_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('read', models.BooleanField(default=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Yeah on post'), (1, 'Yeah on comment'), (2, 'Comment on my post'), (3, "Comment on others' post"), (4, 'Follow to me')])),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='feeling',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, '3ds'), (2, 'wii u'), (3, 'both')], default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'general'), (1, 'game'), (2, 'special')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.SmallIntegerField(choices=[(0, 'normal'), (1, 'happy'), (2, 'wink'), (3, 'surprised'), (4, 'frustrated'), (5, 'confused')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gameskill',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_visibility',
            field=models.SmallIntegerField(choices=[(0, 'show'), (1, 'friends only'), (2, 'hide')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relation_visibility',
            field=models.SmallIntegerField(choices=[(0, 'show'), (1, 'friends only'), (2, 'hide')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yeah',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'post'), (1, 'comment')], default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='context_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='context_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
