# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0024_auto_20170812_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='merged_with',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
