# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0025_notification_merged_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='merged_with',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='closedverse_main.Notification'),
            preserve_default=False,
        ),
    ]
