# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 19:17
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0003_auto_20170729_1914'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
