# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0004_auto_20170729_1917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
