# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0010_auto_20170730_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityClink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('kind', models.BooleanField(default=False)),
                ('also', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='closedverse_main.Community')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='closedverse_main.Community')),
            ],
        ),
    ]
