# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0011_communityclink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='icon',
        ),
        migrations.AddField(
            model_name='community',
            name='platform',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
