# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0013_community_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='icons',
        ),
    ]
