# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0018_remove_community_icol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='community',
            name='ico',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
