# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closedverse_main', '0019_auto_20170730_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='type',
            new_name='kind',
        ),
    ]
